#!/usr/bin/env ruby

require 'getoptlong'

require 'human_readable'
require 'text_output'
require 'directory_node'
require 'directory_inspector'
require 'reducer'

include HumanReadable

SUFFIXES = [' ', 'k', 'm', 'g']
DEFAULT_SIZE = "100m"

opts = GetoptLong.new(
  ["--size", "-s", GetoptLong::REQUIRED_ARGUMENT],
  ["--width", "-w", GetoptLong::REQUIRED_ARGUMENT],
  ["--verbose", "-v", GetoptLong::NO_ARGUMENT],
  ["--one-filesystem", "-x", GetoptLong::NO_ARGUMENT])

opts.each do |opt, arg|
  case opt
  when "--size"
    $size = arg
  when "--width"
    $width = arg.to_i
  when "--verbose"
    $verbose = true
  when "--one-filesystem"
    $one_filesystem = true
  end
end

$path = ARGV[0] ? File.expand_path(ARGV[0]) : File.expand_path(".")
$size = DEFAULT_SIZE if not $size or $size == 0

tree = DirectoryInspector.new($path, {:one_filesystem => $one_filesystem}).run
reduced_tree = Reducer.run(tree, text_to_size($size))
TextOutput.new(reduced_tree, $stdout, {:width => $width, :verbose => $verbose}).print_all(text_to_size($size))
